# Generated by Django 5.2.1 on 2025-06-07 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MathQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200, verbose_name='نص السؤال')),
                ('operation', models.CharField(choices=[('addition', 'جمع'), ('subtraction', 'طرح'), ('multiplication', 'ضرب'), ('division', 'قسمة')], max_length=20, verbose_name='نوع العملية')),
                ('operand1', models.IntegerField(verbose_name='العدد الأول')),
                ('operand2', models.IntegerField(verbose_name='العدد الثاني')),
                ('correct_answer', models.IntegerField(verbose_name='الإجابة الصحيحة')),
                ('difficulty', models.CharField(choices=[('easy', 'سهل'), ('medium', 'متوسط'), ('hard', 'صعب')], default='medium', max_length=10, verbose_name='مستوى الصعوبة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'سؤال رياضي',
                'verbose_name_plural': 'أسئلة رياضية',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المشارك')),
                ('grade', models.CharField(max_length=50, verbose_name='الصف')),
                ('group', models.CharField(blank=True, max_length=50, null=True, verbose_name='المجموعة')),
                ('school', models.CharField(blank=True, max_length=100, null=True, verbose_name='المدرسة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
            ],
            options={
                'verbose_name': 'مشارك',
                'verbose_name_plural': 'مشاركون',
            },
        ),
        migrations.CreateModel(
            name='StudentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100, verbose_name='اسم الطالب')),
                ('grade', models.CharField(max_length=50, verbose_name='الصف')),
                ('session_code', models.CharField(max_length=20, verbose_name='رمز الجلسة')),
                ('difficulty', models.CharField(choices=[('easy', 'سهل'), ('medium', 'متوسط'), ('hard', 'صعب')], default='medium', max_length=10, verbose_name='مستوى الصعوبة')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='وقت البداية')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='وقت الانتهاء')),
                ('is_completed', models.BooleanField(default=False, verbose_name='مكتملة')),
                ('total_questions', models.IntegerField(default=10, verbose_name='إجمالي الأسئلة')),
                ('correct_answers', models.IntegerField(default=0, verbose_name='الإجابات الصحيحة')),
                ('score', models.FloatField(default=0.0, verbose_name='النتيجة')),
            ],
            options={
                'verbose_name': 'جلسة طالب',
                'verbose_name_plural': 'جلسات الطلاب',
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المسابقة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف المسابقة')),
                ('difficulty', models.CharField(choices=[('easy', 'سهل'), ('medium', 'متوسط'), ('hard', 'صعب')], default='medium', max_length=10, verbose_name='مستوى الصعوبة')),
                ('duration_minutes', models.IntegerField(default=30, verbose_name='مدة المسابقة (دقيقة)')),
                ('questions_count', models.IntegerField(default=10, verbose_name='عدد الأسئلة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='منشئ المسابقة')),
            ],
            options={
                'verbose_name': 'مسابقة',
                'verbose_name_plural': 'مسابقات',
            },
        ),
        migrations.CreateModel(
            name='CompetitionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(verbose_name='النتيجة')),
                ('total_questions', models.IntegerField(verbose_name='إجمالي الأسئلة')),
                ('correct_answers', models.IntegerField(verbose_name='الإجابات الصحيحة')),
                ('time_taken', models.FloatField(verbose_name='الوقت المستغرق (دقيقة)')),
                ('algebra_correct', models.IntegerField(default=0, verbose_name='الجبر الصحيح')),
                ('geometry_correct', models.IntegerField(default=0, verbose_name='الهندسة الصحيحة')),
                ('arithmetic_correct', models.IntegerField(default=0, verbose_name='الحساب الصحيح')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإكمال')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competition', verbose_name='المسابقة')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.participant', verbose_name='المشارك')),
            ],
            options={
                'verbose_name': 'نتيجة مسابقة',
                'verbose_name_plural': 'نتائج المسابقات',
            },
        ),
        migrations.CreateModel(
            name='StudentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_answer', models.IntegerField(verbose_name='إجابة الطالب')),
                ('is_correct', models.BooleanField(verbose_name='صحيحة')),
                ('response_time', models.FloatField(verbose_name='وقت الإجابة (ثانية)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإجابة')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.mathquestion', verbose_name='السؤال')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.studentsession', verbose_name='الجلسة')),
            ],
            options={
                'verbose_name': 'إجابة طالب',
                'verbose_name_plural': 'إجابات الطلاب',
            },
        ),
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField(verbose_name='الإجابة')),
                ('is_correct', models.BooleanField(verbose_name='صحيحة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإجابة')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.mathquestion', verbose_name='السؤال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إجابة مستخدم',
                'verbose_name_plural': 'إجابات المستخدمين',
            },
        ),
    ]
